menu:
  Home:
  Archives: archives
  Members: members

widgets:
- search
- category
- tag

excerpt_link: Read More

ogp_image: /images/logo/logo_LIGHT_256.png

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics: UA-173218946-1
rss:


toc:
  maxdepth: 6
  class: toc
  slugify: transliteration
  anchor:
    position: after
    symbol: "#"
    style: header-anchor